LICENSE

chore: add Apache 2 License

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/failing-tests.md
.github/PULL_REQUEST_TEMPLATE.md

This PR introduces PR and issues templates.
As such it fixes #6.

GitHub templates

---

docker/local/Dockerfile

/kind feature
/area examples
It's a docker image for local builds of Falco Exporter. We need it because we plan to use it in a Kubernetes cluster and it may be interesting for others as well.
NONE
It's my first PR here, so feel free to criticize the whole thing.
**Does this PR introduce a user-facing change?**: 
```release-note
new: docker image for local builds
```

new: dockerfile for local builds

---

go.mod
go.sum
pkg/exporter/exporter.go

/kind feature
/area pkg
It updates the Prometheus output to add the hostname field
Fixes #10
**Does this PR introduce a user-facing change?**:
```release-note
adds hostname field in the output
```

feat: add hostname output

---

Makefile
build/Dockerfile

Just a base dockerfile and make target to build the official image.
> /kind bug
> /kind tests
/kind feature
> /area pkg
Fixes #
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

new(build): base dockerfile

---

Makefile
README.md
deploy/helm/falco-exporter/Chart.yaml
deploy/helm/falco-exporter/templates/NOTES.txt
deploy/helm/falco-exporter/templates/_helpers.tpl
deploy/helm/falco-exporter/templates/daemonset.yaml
deploy/helm/falco-exporter/templates/secret-certs.yaml
deploy/helm/falco-exporter/templates/service.yaml
deploy/helm/falco-exporter/templates/serviceaccount.yaml
deploy/helm/falco-exporter/templates/tests/test-connection.yaml
deploy/helm/falco-exporter/values.yaml
deploy/k8s/falco-exporter/README.md
deploy/k8s/falco-exporter/templates/daemonset.yaml
deploy/k8s/falco-exporter/templates/secret-certs.yaml
deploy/k8s/falco-exporter/templates/service.yaml
deploy/k8s/falco-exporter/templates/serviceaccount.yaml

This PR provides the helm chart - but also YAML templates - for deploying in Kubernetes, and related documentation.
> /kind bug
> /kind tests
/kind feature
> /area pkg
This PR provides two convenient methods for deploying in K8s:
- a local helm chart
- YAML templates files (autogenerated)
Documentation included.
Fixes #15 
**Does this PR introduce a user-facing change?**: …

k8s deployment and helm chart

---

.gitignore
.goreleaser.yml
README.md
go.sum
release.md

This PR adds the very first releasing process that will be used for the v0.1.0.
> /kind bug
> /kind tests
/kind feature
> /area pkg
Fixes #14
A fully [automated release process using CircleCI](https://github.com/falcosecurity/falco-exporter/pull/19/files#diff-6cd007d62737e5a12b005b4414d7b899R38) will be introduced within the v0.2.0 release.
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

build: release process

---

README.md
cmd/falco-exporter/root.go

Signed-off-by: Jose Angel Santiago
/kind feature
/area commands
falco-exporter may expose sensitive information through alerts (credentials, endpoints, etc...)
Fixes #47 
First time with Go, I'm completely open to any improvement

Add Mutual TLS feature

---

deploy/k8s/falco-exporter/README.md
deploy/k8s/falco-exporter/templates/daemonset.yaml
deploy/k8s/falco-exporter/templates/service.yaml
deploy/k8s/falco-exporter/templates/serviceaccount.yaml

> /kind bug
/kind cleanup
> /kind tests
> /area pkg
/area examples
This PR follows up #51 and updates the configuration of the probes accordingly. 
Fixes #

update(deploy): new probes configuration

---

cmd/falco-exporter/root.go

/kind bug
> /kind tests
/area commands
> /area pkg
Fixes #

fix(cmd): correct `unix://` prefix check

---

release.md

> /kind bug
> /kind tests
> /area pkg
Fixes #

docs(RELEASE.md): correct slack channel URL

---

README.md

Co-authored-by: Matteo Baiguini <baiguini.matteo@gmail.com>
Fixes #58

docs(README.md): add priority mapping table

---

README.md

suggested link fix in this issue: https://github.com/falcosecurity/falco-exporter/issues/67
Thank you so much @jacks-reid, you can also make this PR and other changes in the future if you wish.  Contribution Guidelines are here: https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md
Signed-off-by: Dan Papandrea <dan.papandrea@sysdig.com>
> /kind bug
> /kind tests
> /area pkg
Fixes #

link fix for getting started

---

build/Dockerfile

Signed-off-by: Mattias Gees <mattias.gees@gmail.com>
/kind bug
> /kind tests
> /area pkg
This bumps to Alpine 3.16 from 3.11 which fixes a zlib CVE
Fixes #

Update Alpine to 3.16

---

README.md
cmd/falco-exporter/root.go
deploy/k8s/falco-exporter/README.md
deploy/k8s/falco-exporter/templates/daemonset.yaml

> /kind bug
/kind cleanup
> /kind tests
/kind feature
/area commands
> /area pkg
Fixes #

update(cmd): default unix socket path for Falco 0.33

---

README.md

/area examples
This PR updates the docs

docs: update docs example

---

.circleci/config.yml

/kind bug
Switch to cimg circle ci go image instead of old unsupported circleci/golang.
Moreover, install goreleaser from repository.
Fixes #

update(ci): multiple release ci fixes

---

.circleci/config.yml
.goreleaser.yml

fix(ci): drop i386 build + add timeout to goreleaser.

---

build/Dockerfile

fix(docker): fixed dockerfile golang version.

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

/kind feature
Ported CI to gha.
Fixes #

new(ci): added gha.

---

.github/workflows/release.yaml
.goreleaser.yml
README.md

new: support arm64 artifacts and docker images.

---

Makefile

> /kind bug
> /kind tests
/kind feature
> /area pkg
/area build
Moves the build command to `BUILD_ARGS` to allow for the user to specify different build args along with the build command. Something like:
```
~/falco-exporter ❯ make GO='CGO_ENABLED=0 go' BUILD_ARGS='build -a -ldflags="-extldflags=-static"'
GCO_ENABLED=0 go build -a -ldflags="-extldflags=-static" ./cmd/falco-exporter
```
Fixes #

Allow use of custom build args

---

Makefile
cmd/falco-exporter/root.go
cmd/falco-exporter/signals.go
pkg/exporter/exporter.go

/area commands
/area pkg
/area examples
See https://github.com/falcosecurity/evolution/issues/318
Fixes #

docs: add license headers and spdx id
